VTchat/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chat.urls'))
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index, name="index"),
    path('health/', views.health_check),
    path("register/",views.register, name="register"),
    path("login/",views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.user_profile, name="profile"),
    path("reset_password/",views.ResetPassword, name='reset_pass'),
    path("suggest/", views.suggest, name="suggest"),
    path("connect/",views.connect,name='connect'),
    path("notifications/", views.notifications, name="notifications"),
    path("connected/",views.connected,name='connected'),
    path("rejected/",views.rejected,name='rejected'),
    path('chat/<str:username>', views.chatuser, name='chat'),
    path('post_files/', views.FileUpload.as_view(), name="post_files"),
     path('download/<int:message_id>/', views.download_file, name='download_file'),
]

chat/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    mobile = models.CharField(max_length=10,unique=True, verbose_name="Mobile Number")
   
    USERNAME_FIELD = "mobile"
    REQUIRED_FIELDS = ["username"]
   

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profiles")
    username = models.CharField(max_length=50, blank=True, null=True)
    mobile = models.CharField(max_length=10)
    first_name = models.CharField(max_length=50, blank=True,null=True)
    last_name = models.CharField(max_length=50, blank=True,null=True)
    profile_pic = models.ImageField(upload_to="img", blank=True, null=True)
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    status = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.username

class connectRequest(models.Model):
    source = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='request_sender')
    dest = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='request_receiver')
    saw = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.source.username} sent {self.dest.username} a connection request"


class ConnectedNotification(models.Model):
    source = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name="Source_Notification")
    dest = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name="Destination_Notification")
    desc = models.TextField(blank=True,null=True)
    accepted = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    saw = models.BooleanField(default=False)

    class Meta:
        ordering = ["-accepted"]

    def __str__(self) -> str:
        return f"{self.source.username} accepted your connection" 



class Message(models.Model):
    source = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_messages')
    dest = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender.username} -> {self.receiver.username} ({self.timestamp})'



class ChatMessage(models.Model):
    source = models.CharField(max_length=100, default=None)
    msg = models.TextField(null=True, blank=True)
    thread = models.CharField(null=True, blank=True, max_length=50)
    file = models.FileField(upload_to='attachment/', blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.msg

chat/forms.py
import imp
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from .models import User  
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import PasswordChangeForm


class Form(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Username', 'class': 'form-control'}),label='User')
    mobile = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Mobile Number', 'class': 'form-control', 'maxlength': '10'}),label='Mobile Number')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter Password', 'class': 'form-control'}),label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'ReEnter Password', 'class': 'form-control'}),label='Confirm Password')
    class Meta:
        model = User
        fields = ["username", "mobile", "password1", "password2"]


class Profile_Form(ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Username', 'class': 'form-control text-white', 'readonly':'','style':'cursor: not-allowed;'}),label='Username')
    mobile = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Mobile Number', 'class': 'form-control text-white', 'maxlength': '10','readonly':'','style':'cursor: not-allowed;'}),label='Mobile Number')
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter First Name', 'class': 'form-control text-white'}),label='First Name')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Last Name', 'class': 'form-control text-white'}),label='Last Name', required=False)

    class Meta:
        model = Profile
        fields = ["username","mobile","first_name","last_name","profile_pic"]


class Reset_Password_Form(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter Old Password', 'class': 'form-control text-white','type' : 'password' }),label='Old Password')
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter new Password', 'class': 'form-control text-white', 'type' : 'password'}), label='New Password',)
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm new password', 'class': 'form-control text-white', 'type' : 'password'}),label='Confirm New Password')
    
    class Meta:
        model = User
        fields = ["old_password","new_password1","new_password2"]
    

chat/views.py
from ast import For
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from .forms import *
from .models import *
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout,get_user_model
from django.contrib.auth.decorators import login_required
import json
from django.views import View
from django.http import HttpResponse
from django.http import FileResponse
from django.contrib.auth.forms import PasswordChangeForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
# Create your views here.

def health_check(request):
    return HttpResponse(status=200)

def get_friends_data(user):
    cur_user = Profile.objects.get(user=user)
    friends = cur_user.friends.all()
    friends_profile_pics = []
    for friend in friends:
        friend_profile = Profile.objects.get(user=friend)
        if friend_profile.profile_pic:
            friends_profile_pics.append(friend_profile.profile_pic.url)
        else:
            friends_profile_pics.append('/static/img/user.png')
    friends_data = zip(friends, friends_profile_pics)
    return friends_data


@login_required(login_url="login")
def index(request):
    friends_data = get_friends_data(request.user)
    cur_user = Profile.objects.get(user=request.user)
    req = connectRequest.objects.filter(dest=request.user)
    context = {
        'friends_data': friends_data,
        'cur_user' : cur_user,
        'notify' : req,
    }
    return render(request,'index.html', context)

def chatuser(request,username):
    friends_data = get_friends_data(request.user)
    cur_user = Profile.objects.get(user=request.user)
    obj = Profile.objects.get(username=username) 
    req = connectRequest.objects.filter(dest=request.user)
    if request.user.id > obj.id:
        thread = f"chat_{request.user.id}-{obj.id}"
    else:
        thread = f"chat_{obj.id}-{request.user.id}"
    msg_obj = ChatMessage.objects.filter(thread = thread)
    context = {
        'friends_data': friends_data,
        'user_obj' : obj,
        'msg_obj' : msg_obj,
        'cur_user' : cur_user,
        'notify' : req,
    }
    return render(request,'chat.html',context)

class FileUpload(View):
    def post(self, request):
        files = request.FILES.get('files')
        message = request.POST.get('message')
        username = request.POST.get('username')
        print(files,message,username)
        try:
            chat_message = ChatMessage.objects.filter(source=username, msg=message).last()
            if chat_message is not None:
                chat_message.file = files
                chat_message.save()
            else:
                return HttpResponse("ChatMessage does not exist.", status=404)
        except Exception as e:
            return HttpResponse(f"An error occurred: {str(e)}", status=500)

        return HttpResponse("File Successfully added!")
    

def download_file(request, message_id):
    chat_message = get_object_or_404(ChatMessage, id=message_id)
    file_path = chat_message.file.path  
    response = FileResponse(open(file_path, 'rb'))
    return response


def register(request):
    if request.user.is_authenticated:
        return redirect("index")
    user = Form()
    if request.method == 'POST':
        user = Form(request.POST)
        if user.is_valid():
            user.save()

            mobile = request.POST['mobile']
            pas = request.POST['password1']
            user_login = authenticate(request, mobile=mobile,password=pas)
            if user_login is not None:
                auth_login(request,user_login)
                return redirect('index')
    return render(request, 'register.html', {'Form':user})


def login(request):
    if request.user.is_authenticated:
        return redirect("index")
    if request.method == 'POST':
        mobile = request.POST['mobile']
        password = request.POST['password']

        user = authenticate(request, mobile = mobile, password = password)

        if user is not None:
            auth_login(request, user)
            return redirect('/')
        else:
            messages.info(request,'Invalid Mobile Number/password')
            return redirect('login') 
    else:
        return render(request, 'login.html')
    
def logout(request):
    auth_logout(request)
    return redirect('login')

@login_required(login_url="login")
def user_profile(request):
    friends_data = get_friends_data(request.user)
    user = request.user
    profile = Profile.objects.get(user=user)
    form = Profile_Form(instance=profile)
    req = connectRequest.objects.filter(dest=request.user)
    if request.method == 'POST':
        form = Profile_Form(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    context = {
        'friends_data': friends_data,
        'form':form,
        'cur_user' : profile,
        'notify' : req,
    }
    return render(request, 'profile.html', context)

def ResetPassword(request):
    if request.method == 'POST':
        reset_form = Reset_Password_Form(request.user, request.POST)
        if reset_form.is_valid():
            reset_form.save()
            return redirect('profile')
    else:
        reset_form = Reset_Password_Form(request.user)
    friends_data = get_friends_data(request.user)
    profile = Profile.objects.get(user=request.user)
    req = connectRequest.objects.filter(dest=request.user)
    context = {
        'friends_data': friends_data,
        'cur_user' : profile,
        'notify' : req,
        'reset_form' : reset_form,
    }
    return render(request, 'reset_pass.html', context=context)

@login_required(login_url="login")
def suggest(request):
    friends_data = get_friends_data(request.user)
    all_profiles = get_user_model()
    user = request.user
    profile = Profile.objects.get(user=user)
    friends = profile.friends.all()
    sugg = all_profiles.objects.exclude(profile__friends__in = friends).exclude(profiles=profile)
    cont_reqst = connectRequest.objects.filter(dest__in = sugg, source = request.user)
    req = connectRequest.objects.filter(dest=user)
    context = {
        'friends_data': friends_data,
        'friends':sugg,
        'users':cont_reqst,
        'cur_user' : profile,
        'notify' : req,
    }
    return render(request, 'suggestions.html',context)

def connect(request):
    content = json.loads(request.body)
    profile = get_user_model()
    dest = profile.objects.get(id = content)
    req = connectRequest.objects.create(source=request.user,dest=dest)
    return JsonResponse("sending....", safe=False)

@login_required(login_url="login")
def notifications(request):
    friends_data = get_friends_data(request.user)
    user = request.user
    cur_user = Profile.objects.get(user=user)
    req = connectRequest.objects.filter(dest=user)
    context = {
        'friends_data' : friends_data,
        'notify' : req,
        'cur_user' : cur_user
    }
    return render(request, 'notification.html',context)


def connected(request):
    data = json.loads(request.body)
    user = get_user_model()
    users = user.objects.get(id = data)
    profile = Profile.objects.get(user_id = request.user.id)
    profile2 = Profile.objects.get(user_id = data)
    req = connectRequest.objects.get(source=users,dest=request.user)
    
    msg = None
    if profile:
        if profile.friends.filter(id=data).exists():
            profile.friends.remove(users)
            msg="no"
        else:
            profile.friends.add(users)
            req.delete()
            notify = ConnectedNotification.objects.create(source=request.user, dest=users, desc=f"{request.user.username} accepted your connection")
            msg="yes"
    if profile2:
        if profile2.friends.filter(id=request.user.id).exists():
            profile2.friends.remove(request.user)
        else:
            profile2.friends.add(request.user)

    return JsonResponse(msg,safe=False)


def rejected(request):
    data = json.loads(request.body)
    user = get_user_model()
    users = user.objects.get(id = data)
    profile = Profile.objects.get(user_id = request.user.id)
    req = connectRequest.objects.get(source=users,dest=request.user)
    try:
        req = connectRequest.objects.get(source=users, dest=request.user)
        req.delete()
    except ObjectDoesNotExist:
        return JsonResponse("Connection request not found.", status=404)

    return JsonResponse("Rejected", safe=False)

chat/templates/chat.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div class="w-100 ps-0 d-flex flex-column justify-content-between vh-100" id="chat-display">
    <div class="d-flex align-items-center justify-content-between p-3 chat-user">
        <a href="{% url 'index'%}" class="text-decoration-none w-100 sm-title"><h4 class="ms-1 fw-bold fs-2">VTchat</h4></a>
        <div class="d-flex align-items-center me-4">
            <div class="img-container">
                <img src="{% if user_obj.profile_pic %}{{ user_obj.profile_pic.url }}{% else %}{% static 'img/user.png' %}{% endif %}" alt="..." class="avatar-img rounded-circle" width="50" height="50">
                    
                    <div class="status {% if user_obj.status %} active {% endif %} position-absolute"></div> </img>
            </div>
            <h5 class="ms-1 fw-bold fs-3 ms-3">{{user_obj.username}}</h5>
        </div>

    </div>
    <div class="message-area text-white py-5 px-3 rounded flex-grow-1" id="chat-body">
        {% for m in msg_obj %}
        {% if m.source == request.user.username %}
            <div class="msg-sent">
                {% if m.file %}
                <div class="attachment d-sm-flex w-auto">
                    <button class="btn attach shadow-none"><i class="bi bi-file-earmark-fill fs-2 text-white"></i></button>
                    <div class="file" style="overflow: hidden;">
                        <h5><a href="{% url 'download_file' m.id %}" download class="fs-5 w-auto text-dark" style="overflow: hidden;">{{m.file}}</a></h5>
                    </div>
                </div>
                {% endif %}
                <span class="msg">{{m.msg}}</span>
                <span class="timestamp">{{m.time|time:'H:i'}}</span>
            </div>
        {% else %}
            <div class="msg-receive">
                {% if m.file %}
                <div class="attachment w-auto d-flex">
                    <button class="btn attach shadow-none"><i class="bi bi-file-earmark-fill fs-2 text-white"></i></button>
                    <div class="file " style="overflow: hidden;">
                        <h5><a href="{% url 'download_file' m.id %}" download class="fs-5 w-auto text-dark" style="overflow: hidden;">{{m.file}}</a></h5>
                    </div>
                </div>
                {% endif %}
                <span class="msg" id="msg_{{m.id}}">{{m.msg}}</span>
                <span class="timestamp">{{m.time|time:'H:i'}}</span>
            </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="p-3 d-flex" id="sm-mb-space">
        <div class="input-group w-auto rounded p-0">
            <input type="file" class="form-control d-none rounded" id="file-input" aria-describedby="file-tooltip" multiple>
            <label for="file-input" type="button" class="btn btn-secondary p-0 rounded" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="send Files">
              <i class="bi bi-paperclip text-white fs-5"></i>
            </label>
            <div id="file-tooltip" class="text-white bg-dark w-auto"></div>
        </div>
        <input type="text" class="shadow-none rounded w-100 mx-2 px-2" id="msg-box" required>
        <input type="hidden" id="message-id" value="{{ user_obj.id }}"> 
        <button class="btn btn-success" id="msg_send" type="submit"><i class="bi bi-send-fill text-white"></i></button>
    </div>
    <div class="bottom-nav justify-content-around align-items-center py-3">
        <i class="bi bi-bell-fill text-white fs-4 fw-bold">
            <span class="badge bg-primary fs-6 rounded">{% if notify|length > 0 %}{{ notify|length }}{% endif %}</span>
        </i>
        <i class="bi bi-person-plus-fill text-white fs-4 fw-bold"></i>
         
        <a href="{% url 'logout' %}" class="text-decoration-none"><i class="bi bi-box-arrow-right text-white fs-4 fw-bold"></i></a>
    </div>
</div>

{{user_obj.id|json_script:"json-username"}}
{{request.user.username|json_script:"json-msg-username"}}
{% endblock %}

chat/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VTchat</title>
    
    <link rel="stylesheet" href="{% static 'style.css' %}">
    
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .form-container {
            background-color: rgb(11, 21, 30);
            border-radius: 10px;
            width: 400px;
        }
        .form-floating input{
            color: #fff !important;
        }
        input::placeholder {
            color: transparent !important;
        }
    </style>
</head>
<body>
    <form method="post" class="form-container p-5">
        {% csrf_token %}
        <h1 class="text-center mb-5">Login</h1>

        {% for i in messages %}
        <div class="alert alert-warning d-flex align-items-center alert-dismissible fade show" role="alert">
            <div> {{i}}</div>
            <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        
        <div class="form-floating mt-5 mb-4">
            <input type="text" class="form-control" name="mobile" id="floatingInput" placeholder="00000 00000" maxlength="10">
            <label for="floatingInput">Mobile Number</label>
          </div>
        
          <div class="form-floating">
            <input type="password" class="form-control" name="password" id="floatingPassword" placeholder="Password" >
            <label for="floatingPassword">Password</label>
        </div>
        <button class="btn btn-primary my-4 w-100" type="submit">Login</button>
        <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
    </form>
</body>
</html>

chat/templates/notification.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div class="w-100 vh-100 d-flex flex-column justify-content-between" id="notifications">
    <div class="d-flex align-items-center mt-3 p-3 chat-user">
        <a href="{% url 'index'%}" class="text-decoration-none w-100 sm-title"><h4 class="ms-1 fw-bold fs-2">VTchat</h4></a>
        <h5 class="ms-1 fw-bold fs-3 text-center w-100">Notifications</h5>
        <div class="w-100 sm-title"></div>
    </div>
    <div class="my-3 mx-3 px-5 list-group flex-grow-1" id="sm-mb-space">
        {% if notify|length > 0 %}
            {% for n in notify %}
            <li class="list-group-item d-sm-flex justify-content-between align-items-center gap-3 py-3">
                <div class="d-flex align-items-center">
                    <img src="{% static 'img/user.png' %}" alt="..." class="avatar-img rounded-circle" width="60" height="60">
                    <div class="ms-2 mt-2 me-auto">
                        <div class="fw-bold">{{n.source.username}}</div>
                        <p>abc</p>
                    </div>
                </div>
                <div class="ms-4 d-flex align-items-center">
                <button class="btn btn-primary me-5 accept" data-id = {{n.source.id}}>Accept</button>
                <button class="btn btn-secondary me-5 reject" data-id = {{n.source.id}}>Reject</button>
                </div>
            </li>
            {% endfor %}
        {% else %}
            <div class="vh-100 d-flex align-items-center justify-content-center">
                <p class="text-secondary fs-5 fw-bold">Empty Notifications</p>
            </div>
        {% endif %}
    </div>
    <div class="bottom-nav d-flex justify-content-around align-items-center py-2">
        <i class="bi bi-bell-fill text-white fs-4 fw-bold">
            <span class="badge bg-primary fs-6 rounded">{% if notify|length > 0 %}{{ notify|length }}{% endif %}</span>
        </i>
        <i class="bi bi-person-plus-fill text-white fs-4 fw-bold"></i>
         
        <a href="{% url 'logout' %}" class="text-decoration-none"><i class="bi bi-box-arrow-right text-white fs-4 fw-bold"></i></a>
    </div>
</div>

{% endblock %}

chat/templates/profile.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div class="w-100 vh-100" id="user-profile" style="overflow-y: auto;">
    <div class="d-flex align-items-center mt-3 p-3 chat-user">
        <a href="{% url 'index'%}" class="text-decoration-none w-100"><h4 class="ms-1 fw-bold fs-2 sm-title">VTchat</h4></a>
        <h5 class="ms-1 fw-bold fs-3 text-center w-100">Profile</h5>
        <div class="w-100"></div>
    </div>
    
    <form class="mt-3 mx-5" method="post" enctype="multipart/form-data" id="sm-mb-space">
    {% csrf_token %}
    
        <div class="text-center mt-5">
            {%if cur_user.profile_pic%}
                <img src="{{cur_user.profile_pic.url}}" alt="user-profile" class="avatar-img rounded-circle" width="200" height="200">
            {%else%}
                <img src="{% static 'img/user.png' %}" alt="user-profile" class="avatar-img rounded-circle" width="200" height="200">
            {% endif %}
            <h2 class="mt-2 text-info fw-bold">{{cur_user.username}}</h2>
        </div>
        <p>If you want to change password <a href="{% url 'reset_pass' %}">click here</a></p>
      {% for field in form %}
            {% if field.errors %}
                <div class="mb-3 w-100">
                    <label for="{{field.id_for_label}}" class="form-label">{{field.label}}</label>
                        {{field}}
                </div>
                {% for i in field.errors %}
                <div class="alert alert-warning d-flex align-items-center alert-dismissible fade show" role="alert">
                    <div> {{i}}</div>
                    <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            {% else %}
                <div class="mb-3 w-100">
                    <label for="{{field.id_for_label}}" class="form-label">{{field.label}}</label>
                    {{field}}
                </div>
            {% endif %}
        {% endfor %}

        <!-- <div class="form-group" style="display: flex; align-items: center;">
            <input type="checkbox" id="change-password" name="change-password">
            <label for="change-password" style="margin-left: 5px;">Change Password</label>
        </div>

        <div id="NewPassword" style="display: none;">
            <div class="mb-3 w-100">
                <label for="id_new_password1" class="form-label">New Password</label>
                <input type="password" class="form-control text-white" placeholder="Enter password">
            </div>
            <div class="mb-3 w-100">
                <label for="id_new_password2" class="form-label">Confirm Password</label>
                <input type="password" class="form-control text-white" placeholder="Enter confirm password">
            </div>
        </div> -->

        <button type="submit" class="btn btn-primary mt-4 mb-5">Update Profile</button>
    </form>
    <div class="bottom-nav d-flex justify-content-around align-items-center py-2">
        <i class="bi bi-bell-fill text-white fs-4 fw-bold">
            <span class="badge bg-primary fs-6 rounded">{% if notify|length > 0 %}{{ notify|length }}{% endif %}</span>
        </i>
        <i class="bi bi-person-plus-fill text-white fs-4 fw-bold"></i>
         
        <a href="{% url 'logout' %}" class="text-decoration-none"><i class="bi bi-box-arrow-right text-white fs-4 fw-bold"></i></a>
    </div>
</div>

{% endblock %}

chat/templates/reset_pass.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div class="w-100 vh-100" id="reset_password" style="overflow-y: auto;">
    <div class="d-flex align-items-center mt-3 p-3 chat-user">
        <a href="{% url 'index'%}" class="text-decoration-none w-100"><h4 class="ms-1 fw-bold fs-2 sm-title">VTchat</h4></a>
        <h5 class="ms-1 fw-bold fs-3 text-center w-100">Reset Password</h5>
        <div class="w-100"></div>
    </div>
    
    <ul class="mx-4 mt-5 text-info">
        <li>Your password can’t be too similar to your other personal information.</li>
        <li>Your password must contain at least 8 characters.</li>
        <li>Your password can’t be a commonly used password.</li>
        <li>Your password can’t be entirely numeric.</li>
    </ul>
    <form class="mt-3 mx-5" method="post" enctype="multipart/form-data" id="sm-mb-space">
        {% csrf_token %}
        

        {% for field in reset_form %}
        {% if field.errors %}
            <div class="mb-3 w-100">
                <label for="{{field.id_for_label}}" class="form-label">{{field.label}}</label>
                    {{field}}
            </div>
            {% for i in field.errors %}
            <div class="alert alert-warning d-flex align-items-center alert-dismissible fade show" role="alert">
                <div> {{i}}</div>
                <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        {% else %}
            <div class="mb-3 w-100">
                <label for="{{field.id_for_label}}" class="form-label">{{field.label}}</label>
                {{field}}
            </div>
        {% endif %}
    {% endfor %}

        <button type="submit" class="btn btn-primary mt-4 mb-5">Reset Password</button>
    </form>
    <div class="bottom-nav d-flex justify-content-around align-items-center py-2">
        <i class="bi bi-bell-fill text-white fs-4 fw-bold">
            <span class="badge bg-primary fs-6 rounded">{% if notify|length > 0 %}{{ notify|length }}{% endif %}</span>
        </i>
        <i class="bi bi-person-plus-fill text-white fs-4 fw-bold"></i>
         
        <a href="{% url 'logout' %}" class="text-decoration-none"><i class="bi bi-box-arrow-right text-white fs-4 fw-bold"></i></a>
    </div>
</div>

{% endblock %}